apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "helm-api-cadastro.labels" . | nindent 4 }}
    {{ .Values.extralabels | nindent 4 }}
data:
  Mongo__host: {{ .Values.envfrom.host }}
  Mongo__DataBase: {{ .Values.envfrom.database }}
  Mongo__port: {{ .Values.envfrom.port | quote }}
