apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-api-cadastro.fullname" . }}-configmap
  labels:
    {{- include "helm-api-cadastro.labels" . | nindent 4 }}
  {{- if not .Values.namespace.enabled }}
  namespace: {{ .Values.namespacedef }}
  {{- else}}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
data:
  Mongo__host: {{ .Values.envfrom.host | quote }}
  Mongo__port: {{ .Values.envfrom.port | quote }}
  Mongo__DataBase: {{ .Values.envfrom.database | quote }}
