apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-api-cadastro.fullname" . }}-service
  labels: 
     {{- include "helm-api-cadastro.labels" . | nindent 5 }}
  {{- if not .Values.namespace.enabled }}
  namespace: {{ .Values.namespacedef }}
  {{- else}}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-api-cadastro.selectorLabels" . | nindent 4 }}
