apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels: 
     {{- include "helm-api-cadastro.labels" . | nindent 5 }}
     {{ .Values.extralabels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-api-cadastro.selectorLabels" . | nindent 4 }}
